name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 New stuff'
    labels:
      - 'enhancement'
  - title: '🐛 Bug/Oddity Fixes'
    labels:
      - 'bug'
      - 'oddity'
  - title: '🧰 Maintenance'
    label: 'maintenance'
    label: 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES
